### ISSUE TITLE
update usuage.md

### ISSUE THREAD

**Issue by justinjeyakani** [gis-rpd/rpd-rnaseq#14]
remove the following  under "Library strandedness "
(Reference format https://github.com/nf-core/rnaseq/blob/master/docs/usage.md)
"""
Specifying --pico makes the pipeline run in forward_stranded mode.

You can set a default in a custom Nextflow configuration file such as one saved in ~/.nextflow/config (see the nextflow docs for more). For example:

params {
    reverse_stranded = true
}
If you have a default strandedness set in your personal config file you can use --unstranded to overwrite it for a given run."
""""

Include the below..
"""
These flags affect the commands used for several steps in the pipeline - namely RSEM and picard collectRnaSeqMetrics
:
RSEM:

--unstranded none 
--forward_stranded forward
--reverse_stranded reverse (Illumina TruSeq Stranded protocols)

Picard collectRnaSeqMetrics:

--unstranded STRAND_SPECIFICITY=NONE
--forward_stranded || singleend STRAND_SPECIFICITY=FIRST_READ_TRANSCRIPTION_STRAND
--reverse_stranded STRAND_SPECIFICITY=SECOND_READ_TRANSCRIPTION_STRAND

""""

**Comment by andreas-wilm** [comment]
fixed in ef299a41c3fd789e2413a4ddc2a73e0c8586fccf
