### ISSUE TITLE
MInor correction required in the main.nf

### ISSUE THREAD

**Issue by justinjeyakani** [gis-rpd/rpd-rnaseq#9]
1.
multiqc trimmgalore report collect missing
not sure why multiqc report only one sample of collectRnaSeqmatrics *RNA_Metrics.txt (AAHHT013)
Please see the results and multiqc report file here..

"/mnt/projects/rpd/devs/justin/rpd-rnaseq-test/results/MultiQC/multiqc_report.html"

2.
repeated arg in collectrnaseqmatrics rule fail the pipeline
     ${arg} \
   need to comment this line ##### # STRAND=SECOND_READ_TRANSCRIPTION_STRAND \
Line No. 379
3.
Linne No. 388
change rseqc results outside the sample_id folder.

**Comment by andreas-wilm** [comment]
Split into several issues
